sudo: required

before_install:
    - docker pull mrokkk/kernel-devel

matrix:
    include:
        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=g++
          services:
            - docker
        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=clang++
          services:
            - docker

language: cpp

script:
    - ./ci.sh

