sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
    - sudo apt-get install binutils gcc-6 g++-6 qemu

cache:
    - ccache

compiler:
    - g++-6

language: cpp

script:
    - mkdir -p build && cd build
    - CXX=g++-6 CC=gcc-6 cmake -DCI_BUILD=ON ..
    - make runqemu -j$(nproc)
    - ./runqemu-nographic

