sudo: required
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - qemu
            - genisoimage

cache:
    - ccache

language: c
compiler: gcc

script:
    - qemu-system-i386 --version
    - qemu-system-i386 --help
    - mkdir -p build && cd build
    - CXX=g++-6 CC=gcc-6 cmake -DCI_BUILD=ON ..
    - VERBOSE=1 make runqemu-iso -j$(nproc)

