sudo: required

before_install:
    - docker pull mrokkk/kernel-devel

matrix:
    include:
        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=g++
          services:
            - docker

        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=clang++
          services:
            - docker

        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=g++
            - OPTIMIZE=ON
          services:
            - docker

        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=g++
            - MULTIBOOT2=ON
          services:
            - docker

        - env:
            - IMAGE=mrokkk/kernel-devel
            - COMPILER=g++
            - OPTIMIZE=ON
            - MULTIBOOT2=ON
          services:
            - docker

language: cpp

script:
    - ./ci/ci.sh

